### ISSUE TITLE
Error:  It seems like you're using a project generated using an old version of the Angular CLI.

### ISSUE THREAD

**Issue by PManager1** [jvandemo/angular2-todo-app#3]
It seems like you're using a project generated using an old version of the Angular CLI.
The latest CLI now uses webpack and has a lot of improvements including a simpler
workflow, a faster build, and smaller bundles.

To get more info, including a step-by-step guide to upgrade the CLI, follow this link:
https://github.com/angular/angular-cli/wiki/Upgrading-from-Beta.10-to-Beta.14

**Comment by jvandemo** [comment]
@jpca999 &mdash; You are right. We are actually rewriting the article and code with the latest version of Angular CLI right now. To be published soon :-)

Thank you!
